# -*- coding: utf-8 -*-
"""rede_neural_mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nR9tb20o5PpL9D7WluWR1jXp-NpW4n-u
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms

print("PyTorch funcionando!")
print("Versão:", torch.__version__)

import torchvision.datasets as datasets
from torch.utils.data import DataLoader

transform = transforms.ToTensor()

trainset = datasets.MNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

trainloader = DataLoader(
    trainset,
    batch_size=64,
    shuffle=True
)

testset = datasets.MNIST(
    root="./data",
    train=False,
    download=True,
    transform=transform
)

testloader = DataLoader(
    testset,
    batch_size=64,
    shuffle=False
)

print("Dataset carregado!")
print("Imagens para treinamento:", len(trainset))
print("Imagens para teste:", len(testset))

class MLP(nn.Module):

    def __init__(self):
        super(MLP, self).__init__()

        self.fc1 = nn.Linear(28 * 28, 10)

    def forward(self, x):

        x = x.view(-1, 28 * 28)

        x = self.fc1(x)

        return x


model = MLP()

print(model)

criterion = nn.CrossEntropyLoss()

optimizer = optim.SGD(
    model.parameters(),
    lr=0.1
)

print("Função de perda e otimizador configurados!")

for epoch in range(3):

    running_loss = 0.0

    for images, labels in trainloader:

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

    print(
        f"Época {epoch + 1}/3 - "
        f"Loss: {running_loss / len(trainloader):.4f}"
    )

correct = 0
total = 0

with torch.no_grad():

    for images, labels in testloader:

        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        total += labels.size(0)

        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total

print(f"Acurácia: {accuracy:.2f}%")